all: 01 02 03 05 06 07 08 09

01: 01.cpp
	g++ 01.cpp -Wall -std=c++11 -o 01exe

02: 02.cpp
	g++ 02.cpp -Wall -std=c++11 -o 02exe
	
03: 03.cpp
	g++ 03.cpp -Wall -std=c++11 -o 03exe
	
05: 05.cpp
	g++ 05.cpp -Wall -std=c++11 -o 05exe
	
06: 06.cpp
	g++ 06.cpp -Wall -std=c++11 -o 06exe
	
07: 07.cpp
	g++ 07.cpp -Wall -std=c++11 -o 07exe
	
08: 08.cpp
	g++ 08.cpp -Wall -std=c++11 -o 08exe
	
09: 09.cpp
	g++ 09.cpp -Wall -std=c++11 -o 09exe
	
	
.PHONY: clean

	clean: -rm -f 01exe 02exe 03exe 05 06 07 08 09