all: 03 04 05 06
	
03: 03.cpp
	g++ 03.cpp -Wall -std=c++11 -o 03exe
	
04: 04.cpp
	g++ 04.cpp -Wall -std=c++11 -o 04exe
	
05: 05.cpp
	g++ 05.cpp -Wall -std=c++11 -o 05exe
	
06: 06.cpp
	g++ 06.cpp -Wall -std=c++11 -o 06exe
	
.PHONY: clean

clean:
	-rm -f 03exe 04exe 05exe 06exe