all:	01 01b	02 03 04 05 06

01:	01.cpp
	g++ 01.cpp -Wall -O2 -std=c++11 -o 01exe

01b:	01b.cpp
	g++ 01b.cpp -Wall -O2 -std=c++11 -o 01bexe

02:	02.cpp
	g++ 02.cpp -Wall -O2 -std=c++11 -o 02exe

03:	03.cpp
	g++ 03.cpp -Wall -O2 -std=c++11 -o 03exe

04:	04.cpp
	g++ 04.cpp -Wall -O2 -std=c++11 -o 04exe

05:	05.cpp
	g++ 05.cpp -Wall -O2 -std=c++11 -o 05exe

06:	06.cpp
	g++ 06.cpp -Wall -O2 -std=c++11 -o 06exe

.PHONY:	clean

clean:
	-rm -f 01exe 01bexe 02exe 03exe 04exe 05exe 06exe
